apiVersion: apps/v1
kind: Deployment
metadata:
 name: oix-platform
spec:
 replicas: 2
 selector:
  matchLabels:
   app: oix
 template:
  metadata:
   labels:
    app: oix
  spec:
   containers:
   - name: oix
     image: oix-platform:latest
     ports:
      - containerPort: 3000
